#149: Moved the API documentation to this repository.
exasol/virtual-schema-common-java pull request #150
Opened 2020-09-17 10:21 UTC by AnastasiiaSergienko

2020-09-22 15:32 UTC, exanm requested changes
I also reviewed the aggregated functions.

We should add some general notice that analytic functions are not included.

2020-09-22 15:32 UTC, exanm commented on doc/development/api/scalar_functions_api.md
> +
````suggestion

### Arithmetic Operators

Arithmetic operators use the common scalar function API, but have special names:

| Function Name | Operation     |
|---------------|---------------|
| NEG           | `-exp1`       |
| ADD           | `exp1 + exp2` |
| SUB           | `exp1 - exp2` |
| MULT          | `exp1 * exp2` |
| FLOAT_DIV     | `exp1 / exp2` |

```json
{
    "type": "function_scalar",
    "numArgs": 2,
    "name": "ADD",
    "infix": true,
    "arguments": [
    {
        ...
    },
    {
        ...
    }
    ]
}
```

````

2020-09-22 15:32 UTC, exanm commented on doc/development/api/scalar_functions_api.md
> +```
```suggestion
```

See above.

2020-09-22 15:32 UTC, exanm commented on doc/development/api/scalar_functions_api.md
> +* [Functions with a variable number of arguments](#functions-with-a-variable-number-of-arguments).
```suggestion
* [Functions with a variable number of arguments](#functions-with-a-variable-number-of-arguments);
```
See below.

2020-09-22 15:32 UTC, exanm commented on doc/development/api/scalar_functions_api.md
> +
```suggestion
* [Arithmetic operators](#arithmetic-operators).

```

2020-09-23 08:58 UTC, AnastasiiaSergienko commented on doc/development/api/virtual_schema_api.md
> +Consistent with scalar functions. To be detailed: `star-operator`, `distinct`, ...
I have no idea what it's supposed to mean

2020-09-23 12:58 UTC, exanm approved these changes
See suggested changes.

2020-09-23 12:58 UTC, exanm commented on doc/development/api/virtual_schema_api.md
> + (requires set-function capability `COUNT` and `COUNT_STAR`)
```suggestion
 (Requires set-function capability `COUNT_STAR`. Please notice, that the set-function capability `COUNT` is not required in this case.)
```

2020-09-23 12:58 UTC, exanm commented on doc/development/api/virtual_schema_api.md
> + (requires set-function capability `COUNT` and `COUNT_DISTINCT`)
```suggestion
 (requires set-function capabilities `COUNT` and `COUNT_DISTINCT`)
```

2020-09-23 12:58 UTC, exanm commented on doc/development/api/virtual_schema_api.md
> +```
```suggestion
```
Not implemented, yet.
```

2020-09-23 12:58 UTC, exanm commented on doc/development/api/virtual_schema_api.md
> + (requires set-function capability `AVG` and `AVG_DISTINCT`)
```suggestion
 (requires set-function capabilities `AVG` and `AVG_DISTINCT`)
```

2020-09-23 12:58 UTC, exanm commented on doc/development/api/virtual_schema_api.md
> +| GROUP_CONCAT        | [GROUP_CONCAT function](#group_concat)             |
```suggestion
| Function Name       | API Mapping Link                                   |
|---------------------|----------------------------------------------------|
| AVG(exp)            | [AVG(exp) function](#avgexp)                       |
| AVG(DISTINCT exp)   | [AVG(DISTINCT exp) function](#avgdistinct-exp)     |
| COUNT(*)            | [COUNT(*) function](#count)                        |
| COUNT(exp)          | [COUNT(exp) function](#countexp)                   |
| COUNT(DISTINCT exp) | [COUNT(DISTINCT exp) function](#countdistinct-exp) |
| GROUP_CONCAT        | [GROUP_CONCAT function](#group_concat)             |
```

2020-09-23 12:58 UTC, exanm commented on doc/development/api/virtual_schema_api.md
> +| REGR_*          | Not included in the API.                |
```suggestion
| Function Name       | Comment                                 |
|---------------------|-----------------------------------------|
| ANY                 | The API uses the SOME function.         |
| CORR                | Not included in the API.                |
| COUNT((exp1, exp2)) | Not included in the API.                |
| COVAR_POP           | Not included in the API.                |
| COVAR_SAMP          | Not included in the API.                |
| GROUPING            | Not included in the API.                |
| LISTAGG             | The API uses the GROUP_CONCAT function. |
| PERCENTILE_CONT     | Not included in the API.                |
| PERCENTILE_DISC     | Not included in the API.                |
| REGR_*              | Not included in the API.                |
```

2020-09-23 12:58 UTC, exanm commented on doc/development/api/virtual_schema_api.md
> +Consistent with scalar functions. To be detailed: `star-operator`, `distinct`, ...
```suggestion
```

2020-09-23 13:23 UTC, exanm approved these changes

2020-09-23 13:35 UTC, merged