doc/156-api-type
exasol/virtual-schema-common-java pull request #221
Opened 2021-03-01 07:50 UTC by jakobbraun

Closes #156

2021-03-01 09:30 UTC, AnastasiiaSergienko requested changes

2021-03-01 09:30 UTC, AnastasiiaSergienko commented on doc/development/api/virtual_schema_api.md
> +The diagram show how Exasol handles Virtual Schema queries: When the core receives an SQL query on a Virtual Schema table, it first checks the capabilities of the corresponding Virtual Schema adapter
```suggestion
The diagram shows how Exasol handles Virtual Schema queries: 

- When the core receives an SQL query on a Virtual Schema table, it first checks the capabilities of the corresponding Virtual Schema adapter. Based on that information it removes all functions and literals that are not supported by the adapter. 
- Next, the Exasol Core sends a query to the Virtual Schema adapter as a `PushdownRequest`. 
- The Virtual Schema adapter now rewrites the query into a new SQL statement that invokes the Exasol importer. The importer statement contains a query to the external database as a string. 
- Next, the Exasol database parses this statement again and invokes the importer. 
- Finally, the Exasol core applies the functions that were not supported by the remote database itself as post processing and returns that result to the SQL client.
```

2021-03-01 09:30 UTC, AnastasiiaSergienko commented on src/uml/requestHandling.puml
> +"Exasol Core" <<-- "Virtual Schema Adapter": "IMPORT FROM JDBC ..."
Import from JDBC is only one example, we can also use IMPORT INTO table, SELECT * FROM VALUESetc.
Maybe you should mention that it's only an example

2021-03-01 09:30 UTC, AnastasiiaSergienko commented on src/uml/requestHandling.puml
> +"SQL Client" <<-- "Exasol Core": rows
Maybe `result` sounds better than rows?

2021-03-01 09:30 UTC, AnastasiiaSergienko commented on src/uml/requestHandling.puml
> +deactivate "Importer"
Please, add a few lines about Importer. It can be hard for a person who doesn't know about VS a lot to understand what is the importer

2021-03-01 09:30 UTC, AnastasiiaSergienko commented on src/uml/requestHandling.puml
> +deactivate "Importer"
And also mention that it's possible to avoid using importer if we use SELECT * FROM VALUES

2021-03-02 13:30 UTC, chiaradiamarcelo commented on README.md
> +A Virtual Schema adapter is basically a UDF. The Exasol core database communicates with this UDF using JSON strings. There are different types of messages, that define the API for a virtual Schema ad
```suggestion
A Virtual Schema adapter is basically a [UDF](https://docs.exasol.com/database_concepts/udf_scripts.htm). The Exasol core database communicates with this UDF using JSON strings. There are different types of messages, that define the API for a virtual Schema adapter ([protocol reference](doc/development/api/virtual_schema_api.md)). This repository wraps this JSON API with a Java API to facilitate the implementation of Virtual Schema adapters in Java.
```

2021-03-08 12:10 UTC, AnastasiiaSergienko approved these changes

2021-03-08 13:25 UTC, merged