* #229: Added missing parsing for the `aggregationType` field of the request
exasol/virtual-schema-common-java pull request #235
Opened 2021-09-02 15:07 UTC by AnastasiiaSergienko

Closes #229

2021-09-07 09:13 UTC, jakobbraun requested changes

2021-09-07 09:13 UTC, jakobbraun commented on src/main/java/com/exasol/adapter/request/renderer/PushdownSqlRenderer.java
> +                if (groupByJson.toString().contains("single_group")) {
that looks dangerous. The json could also contain `single_group` as a column name.

2021-09-07 09:13 UTC, jakobbraun commented on src/main/java/com/exasol/adapter/request/renderer/PushdownSqlRenderer.java
> +                    && ((SqlLiteralString) groupBy.getExpressions().get(0)).getValue().equals("a")) {
what is this condition for? Why do you check if the value is equal to `a`?

2021-09-07 09:13 UTC, jakobbraun commented on src/main/java/com/exasol/adapter/request/renderer/PushdownSqlRenderer.java
> +                return JSON.createObjectBuilder().add("aggregationType", "single_group").build();
is there a reason why you don't use `AGGREGATION_TYPE` here?

2021-09-07 09:13 UTC, jakobbraun commented on src/main/java/com/exasol/adapter/request/parser/PushdownSqlParser.java
> +            return new SqlGroupBy(List.of(new SqlLiteralString("a")));
I think that functionallity does not belong into the parser. As far as I unsersdtand, it's alreaddy an implementation for handling these types of groups. This structure should in ,y oppinion be a representation of the JSON format. Different virtual schemas can then handle it differently.
You could so this transformation in a sepearate class called for example `SingleGroupTransformter`

2021-09-08 09:27 UTC, narmion approved these changes
Perhaps you can add the two additional test cases I suggested.
Besides that, this is ready to merge after you have addressed the open comments.
Thank you for fixing that :pray:

2021-09-24 07:48 UTC, jakobbraun approved these changes

2021-09-24 09:26 UTC, merged